### ISSUE TITLE
Make the Navbar image as a link to the sack site

### ISSUE THREAD

**Issue by YoshithaRathnayake** [acf-sack/sack-blog#38]
**Is your feature request related to a problem? Please describe.**
Currently, the navbar image has no link

**Describe the solution you'd like**
Make the Navbar image as a link to the sack site

**Are you working on this?**
Yes

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by Piumal1999** [comment]
Assigned @YoshithaRathnayake .
With the same pull request, you can fix the remaining navbar issues as well

**Comment by YoshithaRathnayake** [comment]
Thank you @Piumal1999
